= Struttura e interpretazione dei programmi del calcolatore - adattato al JavaScript
Gionata Massi <gionata.massi@savoiabenincasa.it>
v0.1.1, 2020-04-10: Prima bozza con paragrafo 1.1
:description: Struttura e interpretazione dei programmi del calcolatore adattato al JavaScript
:keywords: SICP, JS, JavaScript
:doctype: book
:sectnums:
:icons: font
:autofit-option:
:experimental:
:reproducible:
:toc:
:toclevels: 4
:xrefstyle: short
:imagesdir: img
:stem:
:allow-uri-read:
:cache-uri:
:source-highlighter: rouge
:lang: it
include::attributes.adoc[]
:example-caption!:

// asciidoctor -r asciidoctor-diagram -a attribute-missing=warn --failure-level=WARN sicp-js-it.adoc
// asciidoctor-pdf -r asciidoctor-diagram -r asciidoctor-mathematical -a allow-uri-read -a cache-uri sicp-js-it.adoc

Questo testo è un adattamento in italiano, realizzato con l'auito di Google Translate, del testo https://sicp.comp.nus.edu.sg/[Structure and Interpretation of Computer Programs — JavaScript Adaptation], il quale è, a sua volta, un adattamento della seconda edizione del noto libro di testo di Harold Abelson e Gerald Jay Sussman dal titolo: "Structure and Interpretation of Computer Programs".
Siccome chi ha adattato il testo ritiene che per imparare l'arte della programmazione sia necessario leggere del buon codice, magari quello dei grandi classici come SICP, e di esercitarsi scrivendo altrettando codice, ha integrato il testo con ulteriori esercizi.

include::cap1/cap1_funzioni.adoc[]