[[sec:data-abstraction]]
=== Introduzione all'astrazione dei dati

//In section <<sec:black-box>>, we noted that a function used as an element in creating a more complex function could be regarded not only as a collection of particular operations but also as a functional abstraction. That is, the details of how the function was implemented could be suppressed, and the particular function itself could be replaced by any other function with the same overall behavior. In other words, we could make an abstraction that would separate the way the function would be used from the details of how the function would be implemented in terms of more primitive functions. The analogous notion for compound data is called . Data abstraction is a methodology that enables us to isolate how a compound data object is used from the details of how it is constructed from more primitive data objects.
Nella sezione <<sec:black-box>>, abbiamo notato che una funzione utilizzata come elemento nella creazione di una funzione più complessa potrebbe essere considerata non solo come una raccolta di operazioni particolari ma anche come un'astrazione funzionale. Cioè, i dettagli di come la funzione è stata implementata potrebbero essere soppressi e la particolare funzione stessa potrebbe essere sostituita da qualsiasi altra funzione con lo stesso comportamento generale. In altre parole, potremmo creare un'astrazione che separerebbe il modo in cui la funzione sarebbe usata dai dettagli di come la funzione sarebbe implementata in termini di funzioni più primitive. Viene chiamata la nozione analoga per i dati composti. L'astrazione dei dati è una metodologia che ci consente di isolare il modo in cui un oggetto di dati composto viene utilizzato dai dettagli di come è costruito da oggetti di dati più primitivi.

//The basic idea of data abstraction is to structure the programs that are to use compound data objects so that they operate on ``abstract data.'' That is, our programs should use data in such a way as to make no assumptions about the data that are not strictly necessary for performing the task at hand. At the same time, a ``concrete'' data representation is defined independent of the programs that use the data. The interface between these two parts of our system will be a set of functions, called and , that implement the abstract data in terms of the concrete representation. To illustrate this technique, we will consider how to design a set of functions for manipulating rational numbers.
L'idea di base dell'astrazione dei dati è strutturare i programmi che devono utilizzare oggetti di dati composti in modo che operino su "dati astratti". Cioè, i nostri programmi dovrebbero utilizzare i dati in modo tale da non fare supposizioni sui dati che non sono strettamente necessari per eseguire il compito in questione. Allo stesso tempo, viene definita una rappresentazione "concreta" dei dati indipendentemente dai programmi che utilizzano i dati. L'interfaccia tra queste due parti del nostro sistema sarà un insieme di funzioni, chiamate e, che implementano i dati astratti in termini di rappresentazione concreta. Per illustrare questa tecnica, considereremo come progettare un insieme di funzioni per manipolare numeri razionali.

include::sp11_operazioni_razionali.adoc[]
