== Costruire astrazioni con le funzioni

[quote, John Locke, Saggio sull'intelletto umano - Libro II (Delle Idee) Capitolo XII (Delle idee complesse). 1690.]
____
Gli atti con cui lo spirito esercita il suo potere sulle idee semplici
sono principalmente questi tre:

. _combinare_ varie idee semplici per formarne una complessa; così sono formate tutte le _idee complesse_
.  _mettere assieme_ due idee, semplici o complesse, e giustapporle in modo
da vederle insieme senza unirle; così lo spirito ottiene tutte le sue
_idee di relazioni_;
. _separar_ le idee _da_ tutte le altre che le
accompagnano nella loro esistenza _reale_, e questo si chiama
astrazione: in tal modo sono formate tutte le _idee generali_.
____

Stiamo per studiare il concetto di **processo di calcolo** (((processo, processo di calcolo, processo computazionale))) o _processo
computazionale_. I processi computazionali sono esseri astratti che
vivono nei calcolatori, come _notebook_, _tablet_,
_smartphone_, _navigatori GPS_, dispositivi dello _Internet of things_ e altri dispositivi con microcontrollori. I processi, mentre evolvono, manipolano altri oggetti astratti chiamati *dati*.
L'evoluzione di un processo è diretta da uno schema di regole chiamato
*programma*. Gli uomini creano i programmi per dirigere i processi.
Quando eseguiamo un programma, in effetti, evochiamo gli spiriti del
computer con i nostri incantesimi.

Un processo computazionale è molto simile all'idea che uno stregone ha
di uno spirito. Il processo non può essere visto né toccato. Non è
composto di materia. Tuttavia è reale. Può eseguire lavori
intellettuali. Può rispondere ad alcune domande. Può gestire eventi del
mondo reale erogando denaro in una banca o controllando un braccio
robotico in una fabbrica. I programmi che usiamo per evocare i processi
sono come gli incantesimi di uno stregone. Sono meticolosamente composti
da *espressioni simboliche* in *linguaggi di programmazione* (((linguaggio di programmazione))) arcani ed
esoterici che prescrivono i compiti che vogliamo far eseguire ai nostri
processi.

Un processo computazionale, in un computer che funziona correttamente,
esegue i programmi in modo preciso e accurato. Quindi i programmatori
alle prime armi, così come l'apprendista stregone, devono imparare a capire e
anticipare le conseguenze delle loro parole magiche. Anche piccoli errori
nei programmi (di solito chiamati *bug* o _glitch_) (((bug, glitch))) possono avere
conseguenze complesse e impreviste.

Fortunatamente, imparare a programmare è considerevolmente meno
pericoloso dello studio della stregoneria, perché gli spiriti di cui ci
occupiamo sono confinati nel calcolatore. La programmazione nel mondo
reale, tuttavia, richiede cura, competenza e saggezza. Un piccolo __bug__ in
un programma di progettazione assistita dal computer (Computer Aided
Design, CAD), ad esempio, può portare al catastrofico schianto di un aereo
o al crollo di una diga o all'autodistruzione di un robot industriale.

Gli *ingegneri del software* hanno la capacità di organizzare i programmi
in modo da essere ragionevolmente sicuri che i processi risultanti
eseguiranno i compiti nel modo previsto. Possono anticipare il comportamento dei
loro sistemi. Sanno come *strutturare i programmi* in modo tale che
problemi imprevisti non portino a conseguenze catastrofiche e quando
sorgono problemi, possono eseguire il *debug* dei loro programmi.
Sistemi computazionali ben progettati, come automobili ben progettate o
reattori nucleari, sono progettati in modo *modulare*, in modo che le
parti possano essere costruite, sostituite e messe a punto
separatamente.

[discrete]
=== Programmazione in JavaScript

Abbiamo bisogno di un linguaggio appropriato per descrivere i processi e
useremo a questo scopo il _linguaggio di programmazione_ *((JavaScript))*.
Proprio come i nostri pensieri quotidiani sono generalmente espressi nel
nostro linguaggio naturale (come l'italiano, l'inglese, il francese o
il giapponese) e le descrizioni dei fenomeni quantitativi sono espresse con
notazioni matematiche, il nostro linguaggio per descrivere i processi
computazionali sarà il linguaggio JavaScript.

JavaScript (((JavaScript, storia del))) è stato sviluppato all'inizio degli anni '90 come linguaggio
di programmazione per il controllo del comportamento dei browser del
World Wide Web tramite _script_ (uno script, letteralmente, un copione,
è una descrizione del comportamento da tenere) incorporati
nelle pagine web. Il linguaggio è stata concepito da Brendan Eich(((Eich, Brendan))),
originariamente sotto il nome di _((Mok))a_, poi rinominato _((LiveScript))_ e
infine ((_JavaScript_)). Il nome _JavaScript_ è un marchio di _Oracle
Corporation_.

Nonostante JavaScript sia nato come linguaggio per il controllo dei browser,
esso è un linguaggio di programmazione generico. Un *interprete*
JavaScript è una *macchina che esegue i processi* descritti nel linguaggio
JavaScript. Il primo interprete JavaScript è stato implementato da Eich
presso _Netscape Communications Corporation_, per il browser web
_Netscape Navigator_. Le caratteristiche principali di JavaScript sono
ereditate dai linguaggi *Scheme* e *Self*. _Scheme_ è un dialetto del
*Lisp* ed è stato usato come linguaggio di programmazione per la
versione originale del libro che ispira questa rivisitazione.
Da _Scheme_, JavaScript ha ereditato alcuni principi di progettazione
fondamentali ed è pertanto possibile adattare il modo di ragionare sui problemi
indotto dal Scheme in JavaScript.

JavaScript ha anche una superficiale somiglianza con il linguaggio
*Java*, nonostante l'assonanza del nome; sia Java che JavaScript utilizzano
la struttura a blocchi del *linguaggio C*. Contrariamente a Java e C,
che di solito vengono _compilati_ in linguaggi di livello inferiore, i
programmi JavaScript sono stati inizialmente interpretati dai browser
web. Dopo _Netscape Navigator_, altri browser web hanno fornito
interpreti per il linguaggio, incluso _Microsoft Internet Explorer_, la
cui versione JavaScript è chiamata _JScript_. La popolarità di
JavaScript per il controllo dei browser Web ha dato origine a uno sforzo
di standardizzazione, culminato in *ECMAScript*. La prima edizione dello
standard *ECMAScript* è stata guidata da Guy Lewis Steele Jr. e completata
nel giugno 1997 (Ecma 1997). La sesta edizione, utilizzata in questo
libro, è stata guidata da Allen Wirfs-Brock e adottata dall'Assemblea
Generale dell'ECMA nel giugno 2015.

La pratica di incorporare programmi JavaScript in pagine Web ha
incoraggiato gli sviluppatori di browser Web a implementare interpreti
JavaScript. Man mano che questi programmi diventavano più complessi, gli
interpreti devono diventare più efficienti nell'eseguirli. Oggi essi
usano tecniche sofisticate come la compilazione __Just-In-Time__ (JIT). La
maggior parte dei programmi JavaScript (a partire dal 2020) sono
incorporati nelle pagine Web e interpretati dai browser, ma JavaScript
viene anche utilizzato per risolvere problemi di carattere generale,
spesso usando l'interprete **Node.js**.

Tuttavia, è la capacità dei browser di eseguire programmi JavaScript che
lo rende un linguaggio ideale per una versione online di un libro di
testo di programmazione. L'esecuzione dei programmi facendo clic sugli
elementi di una pagina Web è naturale in JavaScript, dopo tutto quello
per cui è stato progettato JavaScript! Più fondamentalmente, JavaScript
possiede funzionalità che lo rendono un mezzo eccellente per studiare
importanti costrutti di programmazione e strutture di dati e per
metterli in relazione con le caratteristiche linguistiche che li
supportano. Le funzioni di prima classe con visibilità statica, 
caratteristica anche del JavaScript, forniscono accesso diretto e conciso ai meccanismi di
astrazione. La tipizzazione dinamica elimina la necessità di dichiarare
i tipi di dati manipolati dal programma. Oltre a queste considerazioni,
la programmazione in JavaScript è molto divertente.

Puoi provare gli esempi anche sfruttando anche alcune applicazioni web,
che offrono limitati servizi gratuiti.

[[elenco_interpreti,elenco delle webapp che realizzano interpreti JavaScript]]
.Alcune applicazioni web con cui invocare i processi nel linguaggio JavaScript
* https://sourceacademy.nus.edu.sg/playground[	Source Academy playground!]
* https://repljs.com/[REPL JS]
* https://repl.it/languages/javascript[repl.it]
* https://jsconsole.com/[jsconsole]
* https://www.jdoodle.com/execute-nodejs-online/[JDoodle Online NodeJS IDE]
* https://codesandbox.io/[CodeSandox]
* http://neilff.github.io/immutable-repl/[Immutable REPL]
* https://ramdajs.com/repl/[Ramda REPL]

include::p1_elementi_programmazione.adoc[]

include::p2_funzioni_e_processi.adoc[]

