==== Valutazione delle combinazioni mediante operatori

Uno degli obiettivi do questo capitolo è quello di isolare i problemi
relativi alle descrizioni dei processi. Ad esempio, consideriamo che,
nel valutare le combinazioni mediante operatori, l'interprete proceda
come segue.

* Per valutare una combinazione mediante operatori, procedi come segue:
	.  Valuta le espressioni operando della combinazione.
	.  Applicare la funzione indicata dall'operatore agli argomenti che
sono i valori degli operandi.

Anche questa semplice regola illustra alcuni punti importanti sui
processi in generale. Innanzitutto, osserva che il primo passo impone
che per completare il processo di valutazione di una combinazione
mediante operatori dobbiamo prima eseguire il processo di valutazione su
ciascun operando della combinazione mediante operatore. Pertanto, la
regola di valutazione è di natura ricorsiva; cioè include, come uno dei
suoi passi, la necessità di invocare la regola stessa. Notate quanto in
modo conciso l'idea della ricorsione possa essere utilizzata per
esprimere ciò che, nel caso di una combinazione profondamente annidata,
verrebbe altrimenti visto come un processo piuttosto complicato. Ad
esempio, valutare

[source,javascript]
----
(2 + 4 * 6) * (3 + 12);
----

richiede che la regola di valutazione sia applicata a quattro diverse
combinazioni. Possiamo ottenere un'immagine di questo processo
rappresentando la combinazione sotto forma di un *albero*, come mostrato
nella <<fig1_1>>. Ogni combinazione è rappresentata da un nodo con
diramazioni corrispondenti all'operatore e agli operandi della
combinazione mediante operatori. I nodi terminali (ovvero nodi senza
rami che ne derivano) rappresentano operatori o numeri. Osservando la
valutazione in termini di struttura ad albero, possiamo immaginare che i
valori degli operandi si muovano verso l'alto, partendo dai nodi
terminali e poi combinandosi a livelli sempre più alti. In generale,
vedremo che la ricorsione è una tecnica molto potente per trattare
oggetti gerarchici come gli alberi. In effetti, il processo di
produzione e consumo di valori salendo verso l'alto che si ottiene della
regola di valutazione è un esempio di un tipo generale di processo noto
come _tree accumulation_.

.Rappresentazione dell'albero, con illustrazione del valore di ogni sottoespressione
[[fig1_1]]
[blockdiag,ca_fig1_1,svg]
....
blockdiag {
  orientation = portrait


  // (2 + 4 * 6) * (3 + 12);
  390 -> 26;
  390 -> "*";
  390 -> 15;

  26 -> 2;
  26 -> "+";
  26 -> 24;
  24 -> 4;
  24 -> m1;
  24 -> 6;

  15 -> 3;
  p1 [label = "+"];
  15 -> p1;
  15 -> 12;

}
....
// image::https://sicp.comp.nus.edu.sg/chapters/img_javascript/ch1-Z-G-1.svg[pdfwidth=75%]

Successivamente, osserva che l'applicazione ripetuta del primo passaggio
ci porta al punto in cui dobbiamo valutare, non combinazioni mediante
operatori, ma *espressioni primitive* come numeri o nomi.

Ci occupiamo dei casi primitivi stabilendo che

* valori dei numeri sono i numeri rappresentati nella notazione
posizionale in base 10, con il punto per separatore decimale, 
* i valori dei nomi sono gli oggetti associati a quei nomi nell'ambiente.

Notare il ruolo dell'ambiente nel determinare il significato dei nomi
nelle espressioni. In JavaScript, non ha senso parlare del valore di
un'espressione come `x + 1` senza specificare alcuna informazione
sull'ambiente che fornirebbe un significato per il nome `x`.

Si noti che la regola di valutazione sopra indicata non gestisce le
dichiarazioni di costanti. Ad esempio, valutando `const x = 3;` non si
applica l'operatore `=` a due argomenti, uno dei quali è il valore del
nome `x` e l'altro è `3`, poiché lo scopo della dichiarazione costante è
proprio quello di associare `x` a un valore. Cioè, la parte `x = 3`
nella dichiarazione di costante

[source,javascript]
----
const x = 3;
----

non è una combinazione di operatori.

La stringa `const` nella dichiarazione costante è una *parola chiave* in JavaScript. Le parole chiave sono *parole riservate* che hanno un significato
particolare e quindi non possono essere utilizzate come nomi di costante.
Una parola chiave o una combinazione di parole chiave indica all'interprete
JavaScript di trattare la rispettiva dichiarazione in modo speciale.
Ciascuna di queste forme sintattiche ha una propria regola di
valutazione. I vari tipi di dichiarazioni (ciascuna con la relativa
regola di valutazione associata) costituiscono la *sintassi* del
linguaggio di programmazione.

.Forma della dichiarazione di una costante
****
*const* _nome_ = _espressione_
****
