==== Funzioni

Abbiamo identificato in JavaScript alcuni degli elementi che devono
apparire in qualsiasi linguaggio di programmazione:

* I numeri e le operazioni aritmetiche sono dati e funzioni primitivi.
* L'annidamento delle combinazioni fornisce un costrutto per combinare
le operazioni.
* Le dichiarazioni di costante che associano i nomi ai
valori forniscono un costutto di astrazione.

Ora conosceremo le *dichiarazioni di funzione*, una tecnica di
astrazione molto più potente con la quale a un'operazione composta può
essere assegnato un nome, così da considerarla come un'unità di calcolo.

Iniziamo esaminando come esprimere l'idea di quadratura di un numero.
Potremmo dire che, per quadrare un numero, occorre moliplicarlo per se
stesso. Questo è espresso in

[source,javascript]
----
function quadrato (x) {
	return x * x;
}
----

possiamo aiutarci nel modo seguente:

[source,javascript]
----
function quadrato(	x   ) { return	  x		*		   x; }
//  ^	   ^		 ^		 ^		 ^		^		   ^
// Per	quadrare un numero,			 lo moltiplichi per se stesso.
----

Qui abbiamo una funzione composta, a cui è stato dato il nome
`quadrato`. La funzione rappresenta l'operazione di moltiplicare
qualcosa per se stesso. Alla cosa da moltiplicare viene assegnato un
*nome locale*, `x`, che svolge lo stesso ruolo di un pronome nel
linguaggio naturale. La valutazione della _dichiarazione di funzione_
crea questa funzione composta e la associa al nome `quadrato`.

La nostra forma più semplice di una dichiarazione di funzione è

.Forma (ristretta) della dichiarazione di una funzione
****
*function* _nome_ *(* _parametri_ *)* *{ return* _espressione_ *; }*
****

Il nome è un simbolo da associare alla funzione nell'*ambiente*. I
parametri sono i nomi utilizzati nel corpo della funzione per fare
riferimento agli argomenti corrispondenti della funzione. L'espressione
dopo la parola chiave *return* è l'espressione da restituire che
produrrà il valore dell'*applicazione della funzione* quando i parametri
vengono sostituiti dagli argomenti a cui viene applicata la funzione. I
parametri sono raggruppati tra parentesi e separati da virgole, proprio
come sarebbero in una chiamata effettiva alla funzione dichiarata.

Avendo dichiarato la funzione `quadrato`, ora possiamo usarla in
un'*espressione di applicazione di funzione*, che trasformiamo in
un'istruzione usando un punto e virgola:

[source,javascript]
----
quadrato (21);
----

Il nome `quadrato` l'*espressione della funzione* dell'applicazione e 21
è l'*espressione dell'argomento*.

[source,javascript]
----
quadrato (2 + 5);
----

Qui, l'_espressione argomento_ è essa stessa un'espressione composta,
l'_espressione mediante operatore_ `2 + 5`.

[source,javascript]
----
quadrato (quadrato (3));
----

Naturalmente le _espressioni di applicazione_ possono anche servire come
espressioni di argomenti. Possiamo anche usare `quadrato` come un
mattoncino con cui definire altre funzioni. Ad esempio,
latexmath:[$x^2 + y^2$] può essere espresso come

[source,javascript]
----
quadrato (x) + quadrato (y);
----

Possiamo facilmente dichiarare una funzione `somma_di_quadrati` che, dati due
numeri qualsiasi come argomenti, produce la somma dei loro quadrati:

[source,javascript]
----
function somma_di_quadrati (x, y) {
    return quadrato (x) + quadrato (y);
}
----

Ora possiamo usare `somma_di_quadrati` come mattoncino per la
costruzione di ulteriori funzioni:

[source,javascript]
----
function f (a) {
    return somma_di_quadrati (a + 1, a * 2);
}
----

L'applicazione di funzioni come `somma_di_quadrati (3, 4)` è - dopo la
combinazione mediante operatore - il secondo tipo di combinazione di
espressioni in espressioni più grandi che incontriamo. Oltre alle
funzioni composte, JavaScript fornisce una serie di funzioni primitive
integrate nell'interprete. Un esempio è la funzione `Math.log` che
calcola il logaritmo naturale del suo argomento. La valutazione
dell'espressione dell'applicazione `Math.log (1)` produce il numero 0.
Le funzioni primitive vengono utilizzate esattamente allo stesso modo
delle funzioni composte. In effetti, non si può dire guardando la
definizione di `somma_di_quadrati` sopra indicata se il quadrato sia una
funzione primitiva dell'interprete, come `Math.log`, o se sia definito
come una funzione composta.