==== Funzioni come astrazioni nella forma di una scatola nera

La funzione `radice_quadrata` è il nostro primo esempio di un processo definito da
un insieme di funzioni che si definiscono l'una con l'altra. Si noti che
la dichiarazione di `radice_quadrata_iter` è ricorsiva; la funzione è cioè definita
in termini di se stessa. L'idea di poter definire una funzione in
termini di se stessa può essere inquietante; potrebbe non essere chiaro
come una definizione circolare del genere possa avere senso, tanto meno
specificare un processo ben definito che deve essere eseguito da un
computer.

Osserva che il problema del calcolo delle radici quadrate si scompone
naturalmente in una serie di sottoproblemi: come capire se una stima è
abbastanza accurata, come migliorare una stima e così via. Ognuna di
queste attività è svolta da una funzione separata. L'intero programma
`radice_quadrata` può essere visualizzato come un raggruppamento di funzioni
(mostrato nella Figura 1.2) che rispecchia la decomposizione del
problema in sottoproblemi.


.Decomposizione funzionale del programma radice_quadrata
[blockdiag,ca_fig1_2,svg]
....
blockdiag {
  radice_quadrata -> radice_quadrata_iter;
  radice_quadrata_iter -> suff_accurata;
  radice_quadrata_iter -> migliora;
  radice_quadrata_iter -> radice_quadrata_iter;
  suff_accurata -> quadrato;
  suff_accurata -> valore_assoltuto;
  migliora -> valor_medio;
}
....

L'importanza di questa strategia di decomposizione non è semplicemente
quella di dividere il programma in parti. Dopotutto, potremmo prendere
qualsiasi programma di grandi dimensioni e dividerlo in parti: le prime
dieci righe, le successive dieci righe, le successive dieci righe e così
via. Piuttosto, è cruciale che ogni funzione compia un compito
identificabile che può essere usato come modulo nella definizione di
altre funzioni. Ad esempio, quando definiamo la funzione `suff_accurata`
in termini di `quadrato`, siamo in grado di considerare la funzione
`quadrato` come una scatola nera. In quel momento non ci occupiamo di come
la funzione calcola il suo risultato, ma solo del fatto che calcola il
quadrato. I dettagli di come viene calcolato il quadrato possono essere
soppressi, per essere considerati in un secondo momento. In effetti, per
quanto riguarda la funzione `suff_accurata`, il __quadrato__ non è proprio una
funzione ma piuttosto un'astrazione di una funzione, una cosiddetta
**astrazione funzionale**. A questo livello di astrazione, qualsiasi
funzione che calcola il quadrato è ugualmente buona.

Pertanto, considerando solo i valori che restituiscono, le seguenti due
funzioni che quadrano un numero dovrebbero essere indistinguibili.
Ognuno accetta un argomento numerico e produce il quadrato di quel
numero come valore.

[source,javascript]
----
function quadrato (x) {
    ritorna x * x;
}

function quadrato (x) {
    return Math.exp (doppio (Math.log (x)));
}

function doppio (x) {
    return x + x;
}
----

Quindi una funzione dovrebbe essere in grado di sopprimere i dettagli.
Gli utenti della funzione potrebbero non aver scritto la funzione da
soli, ma potrebbero averla ottenuta da un altro programmatore come una
scatola nera. Un utente non dovrebbe avere bisogno di sapere come viene
implementata la funzione per poterla utilizzare.

[discrete]
===== Nomi locali

Un dettaglio dell'implementazione di una funzione che non dovrebbe
interessare all'utente della funzione è la scelta dei nomi da parte
dell'implementatore per i parametri della funzione. Pertanto, le
seguenti funzioni non dovrebbero essere distinguibili:

[source,javascript]
----
function quadrato (x) {
    return x * x;
}

function quadrato (y) {
    return y * y;
}
----

Questo principio - che il significato di una funzione dovrebbe essere
indipendente dai nomi dei parametri usati dal suo autore - sembra evidente
ma ha conseguenze profonde. 
La conseguenza
più semplice è che i nomi dei parametri di una funzione devono essere
locali al corpo della funzione. Ad esempio, abbiamo usato
`quadrato` nella dichiarazione di `suff_accurata` nella nostra funzione
`radice_quadrata`:

[source,javascript]
----
function suff_accurata(stima, x) {
    return valore_assoluto ( quadrato (stima) - x) < 0.001;
}
----

L'intenzione dell'autore di `suff_accurata` è di determinare se il quadrato del
primo argomento rientri in un determinato intorno del secondo
argomento. Vediamo che l'autore di `suff_accurata` ha usato il nome
`stima` per riferirsi al primo argomento e `x` per riferirsi al secondo
argomento. L'argomento di quadrato è `stima`. Se l'autore di `quadrato`
ha usato `x` per fare riferimento al secondo argomento, vediamo
che la `x` in `suff_accurata` deve essere una `x` diversa da quella usata in
`quadrato`. L'esecuzione della funzione `quadrato` non deve influire sul
valore di `x` che viene utilizzato da `suff_accurata`, perché quel valore
di `x` può essere necessario per `suff_accurata` dopo che il calcolo del `quadrato`
è terminato.

Se i parametri non fossero locali ai corpi delle loro rispettive
funzioni, allora il parametro `x` in `quadrato` potrebbe essere confuso con il
parametro `x` in `suff_accurata`, e il comportamento di `suff_accurata`
dipenderebbe da quale versione di `quadrato` abbiamo usato. Pertanto,
`quadrato` non sarebbe la scatola nera che desideravamo.

Un parametro di una funzione ha un ruolo molto speciale nella
dichiarazione di funzione, in quanto non ha importanza il nome del
parametro. Tale nome è chiamato **legame** o _associazione_, __binding__ in inglese,
e diciamo che la dichiarazione
di funzione associa i suoi parametri. Il significato di una dichiarazione
di funzione rimane invariato se un nome associato viene costantemente
rinominato in tutta la dichiarazione. Se un nome non è associato,
diciamo che è libero. L'insieme di espressioni per cui un'associazione
dichiara un nome è chiamato **visibilità**, __scope__ in inglese, di quel nome. In una dichiarazione di
funzione, i nomi associati dichiarati come parametri della funzione
hanno il corpo della funzione come visibilità.

Nella dichiarazione di `suff_accurata` sopra, `stima` e `x` sono nomi
associati ma `valore_assoluto` e `quadrato` sono liberi. Il significato 
di `suff_accurata` dovrebbe essere indipendente dai nomi che scegliamo per `stima` e `x`
fintanto che sono distinti e diversi da `valore_assoluto` e `quadrato`. (Se
rinominassimo `stima` in `valore_assoluto` avremmo introdotto un bug catturando il
nome `valore_assoluto`. Sarebbe cambiato da libero a legato.) Il significato di `suff_accurata`
non è indipendente dalla scelta dei suoi nomi liberi. Dipende
sicuramente dal fatto (esterno a questa dichiarazione) che il simbolo
`valore_assoluto` denota una funzione per calcolare il valore assoluto di un numero.
La funzione JavaScript `valore_assoluto` calcolerà una diversa funzione
matematica se sostituiamo `Math.cos` (funzione coseno di
JavaScript) con `valore_assoluto` nella sua dichiarazione.

[discrete]
===== Dichiarazioni interne e struttura a blocchi

Finora abbiamo un tipo di isolamento del nome a nostra disposizione: i parametri di una funzione
sono locali al corpo della funzione.
Il programma per il calcolo della radice quadrata
illustra un altro modo in cui vorremmo controllare l'uso dei nomi. Il
programma <<radq1>> è costituito da funzioni separate.

Il problema di questo programma è che l'unica funzione importante per gli utenti è
`radice_quadrata`. Le altre funzioni (`radice_quatrata_iter`, `suff_accurata` e `migliora`)
ingombrano solo le loro menti. Non possono dichiarare qualsiasi altra
funzione chiamata `suff_accurata` come parte di un altro programma che opera
insieme con il programma per la radice quadrata, perché la funzione `radice_quadrata` ne ha bisogno.
Il problema è particolarmente grave nella costruzione di grandi sistemi
da parte di molti programmatori separati. Ad esempio, nella costruzione
di una libreria di funzioni numeriche, molte funzioni numeriche
vengono calcolate come approssimazioni successive e quindi potrebbero
avere funzioni gli stessi nomi come funzioni
ausiliarie. Vorremmo localizzare le sottofunzioni, nascondendole
all'interno di `radice_quadrata` in modo che `radice_quadrata` possa coesistere con altre
funzioni basate sulle approssimazioni successive, ognuna con la propria funzione `suff_accurata`.
Per renderlo possibile, consentiamo a una funzione di avere
dichiarazioni interne locali a tale funzione. Ad esempio, nel problema
della radice quadrata possiamo scrivere


[source, javascript]
----
// MODIFICARE. NON HO FATTO LA RISCRITTURA
function radice_quadrata_iter (stima, x) {
    return suff_accurata (stima, x)
           ? stima
           : radice_quadrata_iter (migliora (stima, x), x);
}

function migliora (stima, x) {
    return valor_medio (stima, x / stima);
}

function valor_medio (x, y) {
    return (x + y) / 2;
}

function suff_accurata (stima, x) {
    return valore_assoluto (quadrato (stima) - x) < 0.001;
}

function radice_quadrata (x) {
    return radice_quadrata_iter (1, x);
}

function valore_assoluto (x) {
    return x >= 0 ? x : -x;
}

function quadrato (x) {
    return x * x;
}
----


                                                    Il corpo di una
funzione - un'istruzione racchiusa tra parentesi graffe - è chiamato
blocco. Le dichiarazioni di funzione nidificate all'interno di un blocco
sono locali per quel blocco. Questa struttura a blocchi è
sostanzialmente la giusta soluzione al più semplice problema di
impacchettamento del nome. Ma c'è un'idea migliore in agguato qui. Oltre
a internalizzare le dichiarazioni delle funzioni ausiliarie, possiamo
semplificarle. Poiché x è associato nella dichiarazione di sqrt, le
funzioni_ abbastanza buone, migliorate e sqrt _iter, che sono definite
internamente a sqrt, rientrano nell'ambito di x. Pertanto, non è
necessario passare x in modo esplicito a ciascuna di queste funzioni.
Invece, consentiamo a x di essere un nome libero nelle dichiarazioni
interne, come mostrato di seguito. Quindi x ottiene il suo valore
dall'argomento con cui viene chiamata la funzione che racchiude sqrt.
Questa disciplina si chiama scoping lessicale.      funzione sqrt (x) \{
    abbastanza buono_ (indovina) \{         ritorno abs (quadrato
(ipotesi) - x) <0,001;     }     funzione migliorare (indovinare) \{
        media di ritorno (indovina, x / indovina);     }     function
sqrt _iter (indovina) \{         restituisce abbastanza_ abbastanza
(indovina)                ? indovina                : sqrt <_> iter
(migliora (indovina));    }    return sqrt_iter (1.0); }
                                                    Useremo ampiamente
la struttura a blocchi per aiutarci a suddividere grandi programmi in
pezzi trattabili. [4] L'idea della struttura a blocchi è nata con il
linguaggio di programmazione Algol 60. Appare nella maggior parte dei
linguaggi di programmazione avanzati ed è uno strumento importante per
aiutare a organizzare la costruzione di programmi di grandi dimensioni.

==== Functions as Black-Box Abstractions

The function sqrt is our first example of a process defined by a set of
mutually defined functions. Notice that the declaration of sqrt_iter is
recursive; that is, the function is defined in terms of itself. The idea
of being able to define a function in terms of itself may be disturbing;
it may seem unclear how such a circular definition could make sense at
all, much less specify a well-defined process to be carried out by a
computer. This will be addressed more carefully in section 1.2. But
first let's consider some other important points illustrated by the sqrt
example.

Observe that the problem of computing square roots breaks up naturally
into a number of subproblems: how to tell whether a guess is good
enough, how to improve a guess, and so on. Each of these tasks is
accomplished by a separate function. The entire sqrt program can be
viewed as a cluster of functions (shown in Figure 1.2) that mirrors the
decomposition of the problem into subproblems.

Figure 1.2 Functional decomposition of the sqrt program.

The importance of this decomposition strategy is not simply that one is
dividing the program into parts. After all, we could take any large
program and divide it into parts—the first ten lines, the next ten
lines, the next ten lines, and so on. Rather, it is crucial that each
function accomplishes an identifiable task that can be used as a module
in defining other functions. For example, when we define the good_enough
function in terms of square, we are able to regard the square function
as a black box. We are not at that moment concerned with how the
function computes its result, only with the fact that it computes the
square. The details of how the square is computed can be suppressed, to
be considered at a later time. Indeed, as far as the good_enough
function is concerned, square is not quite a function but rather an
abstraction of a function, a so-called functional abstraction. At this
level of abstraction, any function that computes the square is equally
good.

Thus, considering only the values they return, the following two
functions squaring a number should be indistinguishable. Each takes a
numerical argument and produces the square of that number as the value.

 function square(x) \{ return x * x; } function square(x) \{ return
math_exp(double(math_log(x))); } function double(x) \{ return x + x; }

So a function should be able to suppress detail. The users of the
function may not have written the function themselves, but may have
obtained it from another programmer as a black box. A user should not
need to know how the function is implemented in order to use it.

Local names One detail of a function's implementation that should not
matter to the user of the function is the implementer's choice of names
for the function's parameters. Thus, the following functions should not
be distinguishable:

 function square(x) \{ return x * x; } function square(y) \{ return y *
y; }

This principle—that the meaning of a function should be independent of
the parameter names used by its author—seems on the surface to be
self-evident, but its consequences are profound. The simplest
consequence is that the parameter names of a function must be local to
the body of the function. For example, we used square in the declaration
of good_enough in our square-root function :

 function good_enough(guess, x) \{ return abs(square(guess) - x) <
0.001; }

The intention of the author of good_enough is to determine if the square
of the first argument is within a given tolerance of the second
argument. We see that the author of good_enough used the name guess to
refer to the first argument and x to refer to the second argument. The
argument of square is guess. If the author of square used x (as above)
to refer to that argument, we see that the x in good_enough must be a
different x than the one in square. Running the function square must not
affect the value of x that is used by good_enough, because that value of
x may be needed by good_enough after square is done computing.

If the parameters were not local to the bodies of their respective
functions, then the parameter x in square could be confused with the
parameter x in good_enough, and the behavior of good_enough would depend
upon which version of square we used. Thus, square would not be the
black box we desired.

A parameter of a function has a very special role in the function
declaration, in that it doesn't matter what name the parameter has. Such
a name is called bound, and we say that the function declaration binds
its parameters. The meaning of a function declaration is unchanged if a
bound name is consistently renamed throughout the declaration.[2] If a
name is not bound, we say that it is free. The set of expressions for
which a binding declares a name is called the scope of that name. In a
function declaration, the bound names declared as the parameters of the
function have the body of the function as their scope.

In the declaration of good_enough above, guess and x are bound names but
abs, and square are free. The meaning of good_enough should be
independent of the names we choose for guess and x so long as they are
distinct and different from abs, and square. (If we renamed guess to abs
we would have introduced a bug by capturing the name abs. It would have
changed from free to bound.) The meaning of good_enough is not
independent of the choice of its free names, however. It surely depends
upon the fact (external to this declaration) that the symbol abs names a
function for computing the absolute value of a number. The JavaScript
function good_enough will compute a different mathematical function if
we substitute math_cos (JavaScript's cosine function) for abs in its
declaration.

Internal declarations and block structure We have one kind of name
isolation available to us so far: The parameters of a function are local
to the body of the function. The square-root program illustrates another
way in which we would like to control the use of names. The existing
program consists of separate functions :

 function sqrt(x) \{ return sqrt_iter(1.0, x); } function
sqrt_iter(guess, x) \{ return good_enough(guess, x) ? guess :
sqrt_iter(improve(guess, x), x); } function good_enough(guess, x) \{
return abs(square(guess) - x) < 0.001; } function improve(guess, x) \{
return average(guess, x / guess); }

The problem with this program is that the only function that is
important to users of sqrt is sqrt. The other functions (sqrt_iter,
good_enough, and improve) only clutter up their minds. They may not
declare any other function called good_enough as part of another program
to work together with the square-root program, because sqrt needs it.
The problem is especially severe in the construction of large systems by
many separate programmers. For example, in the construction of a large
library of numerical functions, many numerical functions are computed as
successive approximations and thus might have functions named
good_enough and improve as auxiliary functions. We would like to
localize the subfunctions, hiding them inside sqrt so that sqrt could
coexist with other successive approximations, each having its own
private good_enough function. To make this possible, we allow a function
to have internal declarations that are local to that function. For
example, in the square-root problem we can write

 function sqrt(x) \{ function good_enough(guess, x) \{ return
abs(square(guess) - x) < 0.001; } function improve(guess, x) \{ return
average(guess, x / guess); } function sqrt_iter(guess, x) \{ return
good_enough(guess, x) ? guess : sqrt_iter(improve(guess, x), x); }
return sqrt_iter(1.0, x); }

The body of a function—a statement enclosed in curly braces—is called a
block. Function declarations nested inside a block are local to that
block. This block structure is basically the right solution to the
simplest name-packaging problem. But there is a better idea lurking
here. In addition to internalizing the declarations of the auxiliary
functions, we can simplify them. Since x is bound in the declaration of
sqrt, the functions good_enough, improve, and sqrt_iter, which are
defined internally to sqrt, are in the scope of x. Thus, it is not
necessary to pass x explicitly to each of these functions. Instead, we
allow x to be a free name in the internal declarations, as shown below.
Then x gets its value from the argument with which the enclosing
function sqrt is called. This discipline is called lexical scoping.

 function sqrt(x) \{ function good_enough(guess) \{ return
abs(square(guess) - x) < 0.001; } function improve(guess) \{ return
average(guess, x / guess); } function sqrt_iter(guess) \{ return
good_enough(guess) ? guess : sqrt_iter(improve(guess)); } return
sqrt_iter(1.0); }

We will use block structure extensively to help us break up large
programs into tractable pieces.[4] The idea of block structure
originated with the programming language Algol 60. It appears in most
advanced programming languages and is an important tool for helping to
organize the construction of large programs.
