==== Esercizi aggiuntivi

==== 
Si scriva una funzione `perimetro_triangolo` che calcola il perimetro di un triangolo
e che ha tre argomenti che si riferiscono alle misure dei lati;
====

==== 
Si scriva una funzione `perimetro_trapezio_rettangolo` che calcola il perimetro di un trapezio
rettangolo dati tre argomenti che si riferiscono alle misure dei lati
perpendicolari tra loro, nell'ordine __base minore__, __base maggiore__ e
altezza;
====

====
Si considereri la generica equazione di secondo grado 
latexmath:[a x^2 + b x + c = 0] di cui vuoi calcolare il valore
latexmath:[x_1=\frac{-b-\sqrt{b^2-4 a c}}{2 a}] supponendo
che il discriminante sia un numero non negativo.

Scrivi la funzione `risolvi_eq2` che ha come argomenti i
coefficienti `a` e `b` e il termine noto `c`.
====

====
Si vuole determinare il valore assunto dal polinomio 
latexmath:[a x^3 + b x^2 + c x + d] quando assegnamo
un valore ad latexmath:[x].

Si scriva la funzione `valuta_polinomio3` che ha per
argomenti i numeri `a`, `b`, `c`, `d` e `x`, sfruttando
l'idea che

latexmath:[p(x) = a x^3 + b x^2 + c x + d = (((a x + b) x + c) x + d)]

e che tale riscrittura ha come sotto-problema comune il
calcolo di latexmath:[a^\prime x + b^\prime].
====

====
Si scriva la funzione `minimo` che restituisce il minimo tra
i valori dei due argomenti.
====

====
Si scriva la funzione `massimo3` che restituisce il massimo tra
i valori dei suoi 3 argomenti. Per calcolarlo usa la funzione
`massimo` che calcola il massimo tra due argomenti.

Considera che latexmath:[\max(a, b, c) = \max(\max(a, b), c)].
====

====
Si scriva una funzione `somma_fino_a` con un argomento `n`
che somma tutti i numeri naturali compresi tra 1 e `n`.
====

====
Si scriva una funzione che somma tutti i termini del tipo
latexmath:[2^{-n}, n \in \mathbb{N}] arrrestandosi quando il prossimo addendo
è inferiore a latexmath:[10^{-16}].

Il valore da trovare approssima latexmath:[1 + \frac{1}{2} + \frac{1}{4} + \frac{1}{8} + \frac{1}{16} + \cdots]
====

====
Scrivere una funzione `pi` che calcola il quadruplo della
sua funzione definita internamente `pi_quarti`.

`pi_quarti` calcola la somma a segni alterni dei reciproci
dei numeri naturali dispari partendo da latexmath:[+1],
ossia

latexmath:[1 - \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + \frac{1}{9} - \cdots]

Come criterio di arresto considera che la distanza tra il
valore già calcolato e il prossimo valore non deve essere
maggiore di latexmath:[10^{-6}].
====