==== Esercizi aggiuntivi

.Esercizio A-1.1.{counter:es_agg_1_1}
====
Costruire un glossario dei termini in cui raccogliere le definizioni
che si trovano in questo sotto-paragrafo.

Il glossario ha la forma:

[options="header"]
|====
|Termine | Sinonimi | Descrizione | Termini collegati
|		|		  |			 |
|====
====

.Esercizio A-1.1.{counter:es_agg_1_1}
====
Costruire una mappa mentale che includa i termini definiti nell'esercizio
precedente.
====

.Esercizio A-1.1.{counter:es_agg_1_1}
====
Scrivere un esercizio di programmazione significativo che possa essere
risolto con le conoscenze apprese in questo sotto-paragrafo.
Esibire il codice che dimostra che l'esercizio può essere effettivamente
risolto.
====

.Esercizio A-1.1.{counter:es_agg_1_1}
==== 
Scrivere tre espressioni semplici e tre espressioni composte mediante operatori che usano gli stessi numerali.
====

.Esercizio A-1.1.{counter:es_agg_1_1}
==== 
Aggiungere le parentesi alle espressioni sottostanti per indicare l'ordine di valutazione usato dall'interprete _JavaScript_.

. 1 + 2 - 3 * 4 / 5
. 1 * 2 + 3 * 4 - 5
. 1 / 2 + 3 * 4 - 5
. 1 + 2 * 3 * 4 - 5 
====

.Esercizio A-1.1.{counter:es_agg_1_1}
==== 
Aggiungere le parentesi alle espressioni sottostanti per indicare l'ordine di valutazione usato dall'interprete _JavaScript_.

. 100000 * 200000 * 400000 / 3 * 10
. 100000 / 3 * 200000 * 400000 * 10

Il valore restituito dall'interprete _JavaScript_ è quello denotato dall'espressione matematica (latexmath:[\frac{8}{3} \cdot 10^{16} = 2,\bar{6}\cdot 10^{16}])? È lo stesso per entrambe le espressioni? Se no, sai spiegarti il perché?
====

.Esercizio A-1.1.{counter:es_agg_1_1}
==== 
Aggiungere le parentesi alle espressioni sottostanti per indicare l'ordine di valutazione usato dall'interprete _JavaScript_.

. 100000 * 200000 * 400000 / 3 * 10 + 1
. 100000 * 200000 * 400000 / 3 * 10 + 1 + 1
. 100000 * 200000 * 400000 / 3 * 10 + 1 + 1 + 1
. 100000 * 200000 * 400000 / 3 * 10 + 1 + 1 + 1 + 1
. 100000 * 200000 * 400000 / 3 * 10 + 1 + 1 + 1 + 1 + 1

Il valore restituito dall'interprete _JavaScript_ è quello denotato dall'espressione matematica? Se no, sai spiegarti il perché?
====

// Dichiarare alcune costanti con espressioni semplici
.Esercizio A-1.1.{counter:es_agg_1_1}
==== 
Dichiarare i valori costanti della tabella seguente:

|====
|Nome        | Valore
|raggio      a| 1
|pi_greco    a| 3.141592653589793
|diametro    a| 2 · raggio
|perimetro   a| pi_greco · diametro
|area        a| pi_greco · raggio^2^
|====

Verificare che abbiano il valore atteso.
====

// Valore undefined come valore restituito dalla dichiarazione di costante
.Esercizio A-1.1.{counter:es_agg_1_1}
==== 
Dichiara una costante `E` di valore 2.718281828459045.
Quale valore viene restituito dalla dichiarazione? Quale valore è prodotto dalla valutazione di `E`?
====

// Valore undefined come valore restituito dalla sequenza di istruzioni
.Esercizio A-1.1.{counter:es_agg_1_1}
==== 
Quale valore viene restituito dalla seguente sequenza di istruzioni?

[source,javascript]
----
1 + 2;
3;
4 * 5;
----
====

// Disegnare l'albero di valutazione di un'espressione non triviale
.Esercizio A-1.1.{counter:es_agg_1_1}
==== 
Disegna l'albero di valutazione per la seguente espressione?

[source,javascript]
----
2 * 10 - 19.62 * 7;
----
====

.Esercizio A-1.1.{counter:es_agg_1_1}
==== 
Si scriva una funzione `perimetro_triangolo` che calcola il perimetro di un triangolo
e che ha tre argomenti che si riferiscono alle misure dei lati;

La si applichi per conoscere il perimetri di un triangolo di lati 3, 4 e 5 m.
====

.Esercizio A-1.1.{counter:es_agg_1_1}
==== 
Si scriva una funzione `perimetro_trapezio_rettangolo` che calcola il perimetro di un trapezio
rettangolo dati tre argomenti che si riferiscono alle misure dei lati
perpendicolari tra loro, nell'ordine __base minore__, __base maggiore__ e
altezza.

Si applici la procedura su almeno tre trapezi per evitare che la funzione sia palesemente errata.
====

.Esercizio A-1.1.{counter:es_agg_1_1}
====
Si considereri la generica equazione di secondo grado 
latexmath:[a x^2 + b x + c = 0] di cui vuoi calcolare il valore
latexmath:[x_1=\frac{-b-\sqrt{b^2-4 a c}}{2 a}] supponendo
che il discriminante sia un numero non negativo.

Scrivi la funzione `risolvi_eq2` che ha come argomenti i
coefficienti `a` e `b` e il termine noto `c`.
====

.Esercizio A-1.1.{counter:es_agg_1_1}
====
Si vuole determinare il valore assunto dal polinomio 
latexmath:[a x^3 + b x^2 + c x + d] quando assegnamo
un valore ad latexmath:[x].

Si scriva la funzione `valuta_polinomio3` che ha per
argomenti i numeri `a`, `b`, `c`, `d` e `x`, sfruttando
l'idea che

latexmath:[p(x) = a x^3 + b x^2 + c x + d = (((a x + b) x + c) x + d)]

e che tale riscrittura ha come sotto-problema comune il
calcolo di latexmath:[a^\prime x + b^\prime].
====

.Esercizio A-1.1.{counter:es_agg_1_1}
====
Si scriva la funzione `minimo` che restituisce il minimo tra
i valori dei due argomenti.
====

.Esercizio A-1.1.{counter:es_agg_1_1}
====
Si scriva la funzione `massimo3` che restituisce il massimo tra
i valori dei suoi 3 argomenti. Per calcolarlo usa la funzione
`massimo` che calcola il massimo tra due argomenti.

Considera che latexmath:[\max(a, b, c) = \max(\max(a, b), c)].
====

.Esercizio A-1.1.{counter:es_agg_1_1}
====
Si scriva una funzione `somma_fino_a` con un argomento `n`
che somma tutti i numeri naturali compresi tra 1 e `n`.
====

.Esercizio A-1.1.{counter:es_agg_1_1}
====
Si scriva una funzione che somma tutti i termini del tipo
latexmath:[2^{-n}, n \in \mathbb{N}] arrrestandosi quando il prossimo addendo
è inferiore a latexmath:[10^{-16}].

Il valore da trovare approssima latexmath:[1 + \frac{1}{2} + \frac{1}{4} + \frac{1}{8} + \frac{1}{16} + \cdots]
====

.Esercizio A-1.1.{counter:es_agg_1_1}
====
Scrivere una funzione `pi` che calcola il quadruplo della
sua funzione definita internamente `pi_quarti`.

`pi_quarti` calcola la somma a segni alterni dei reciproci
dei numeri naturali dispari partendo da latexmath:[+1],
ossia

latexmath:[1 - \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + \frac{1}{9} - \cdots]

Come criterio di arresto considera che la distanza tra il
valore già calcolato e il prossimo valore non deve essere
maggiore di latexmath:[10^{-6}].
====
