[[sec:lambda]]
==== Costruire le funzioni utilizzando le espressioni Lambda

//In using `sum` as in section [sec:procedures-as-parameters], it seems terribly awkward to have to declare trivial functions such as `pi_term` and `pi_next` just so we can use them as arguments to our higher-order function. Rather than declare `pi_next` and `pi_term`, it would be more convenient to have a way to directly specify ``the function that returns its input incremented by 4'' and ``the function that returns the reciprocal of its input times its input plus 2.'' We can do this by introducing _lambda expressions_ as a syntactic form for creating functions. Using lambda expressions, we can describe what we want as
Nell'usare `somma` come nel <<sec:procedures-as-parameters>>, sembra terribilmente imbarazzante dover dichiarare funzioni banali come `pi_termine` e `pi_prossimo` soltanto perché così possiamo usarle come argomenti per la nostra funzione di ordine superiore. Piuttosto che dichiarare `pi_prossimo` e `pi_termine`, sarebbe più conveniente avere un modo per specificare direttamente "la funzione che restituisce il suo input incrementato di 4" e "la funzione che restituisce il reciproco del suo input per il suo input più 2". Possiamo farlo introducendo _espressioni lambda_ come forma sintattica per la creazione di funzioni. Usando le espressioni lambda, possiamo descrivere ciò che vogliamo come

[source,javascript]
----
x => x + 4;
----

//and
e

[source,javascript]
----
x => 1.0 / (x * (x + 2));
----

//Then our `pi_sum` function can be expressed without declaring any auxiliary functions as
Quindi la nostra funzione `somma_pi` può essere espressa senza dichiarare alcuna funzione ausiliaria come

[source,javascript]
----
function somma_pi(a, b) {
    return somma(x => 1.0 / (x * (x + 2)),
               a,
               x => x + 4,
               b);
}
----

//Again using a lambda expression, we can write the `integral` function without having to declare the auxiliary function `add_dx`:
Usando ancora un'espressione lambda, possiamo scrivere la funzione `integrale` senza dover dichiarare la funzione ausiliaria `aggiungi_dx`:

[source,javascript]
----
function integrale(f, a, b, dx) {
    return somma(f,
               a + dx / 2.0,
               x => x + dx,
               b)
           *
           dx;
}
----

//In general, lambda expressions are used to create functions in the same way as function declarations, except that no name is specified for the function and the return keyword and curly braces are omitted.footnote:[If there is only one parameter, the parentheses around the parameter list can also be omitted. In section [sec:graphics], we will extend the syntax of lambda expressions to allow blocks as bodies, as in function declaration statements.]
In generale, le espressioni lambda vengono utilizzate per creare funzioni allo stesso modo delle dichiarazioni di funzione, tranne per il fatto che non viene specificato alcun nome per la funzione e la parola chiave return e le parentesi graffe vengono omesse.footnote:[Se è presente un solo parametro, le parentesi intorno all'elenco dei parametri possono anche essere omesse. Nel TODO sec:graphics, estenderemo la sintassi delle espressioni lambda per consentire di avere i blocchi come corpo, come nelle dichiarazioni di dichiarazione di funzione.]

.Forma della dichiarazione di una espressione lambda
****
**(** _parametri_ **) => ** _espressione_
****

//The resulting function is just as much a function as one that is created using a function declaration statement. The only difference is that it has not been associated with any name in the environment. We consider
La funzione risultante è una funzione tanto quanto quella creata utilizzando un'istruzione di dichiarazione di funzione. L'unica differenza è che non è stato associato ad alcun nome nell'ambiente. Noi consideriamo

[source,javascript]
----
function piu4(x) { 
    return x + 4; 
}
----

//to be equivalent tofootnote:[In JavaScript, there are subtle differences between the two versions: Function declaration statements are ``hoisted'' (automatically moved) to the beginning of the surrounding block, whereas constant declarations are not, and names declared with function declaration can be re-assigned using assignment (see chapter [sec:assignment]). In this book, we are avoiding these features and shall treat function declarations as equivalent to the corresponding constant declaration.]
[[foot:function-decl-vs-lambda]]
essere equivalente a footnote:[In JavaScript ci sono sottili differenze tra le due versioni: le istruzioni di dichiarazione di funzione (**function __nome__**) sono __sollevate__ (__hoisted__, spostate automaticamente) all'inizio del blocco circostante, mentre le dichiarazioni di costanti non lo sono, e i nomi dichiarati con le dichiarazioni di funzione (**const __nome__ = ( __parametri__ ) => __espressione__**) possono essere riassegnata usando l'assegnazione (vedi TODO sec:assegnazione).]
// In questo libro, stiamo evitando queste caratteristiche e tratteremo le dichiarazioni di funzione come equivalenti alla corrispondente dichiarazione di costante.]

[source,javascript]
----
const piu4 = x => x + 4;
----

//We can read a lambda expression as follows:
Possiamo leggere un'espressione lambda come segue:

[source,javascript]
----
//                         x       =>             x     +   4
//                         ^       ^              ^     ^   ^
//                         |       |              |     |   |
// la funzione di argomento x che restituisce il valore piu' 4
----

//Like any expression that has a function as its value, a lambda expression can be used as the function expression in an application such as
Come qualsiasi espressione che ha una funzione come valore, un'espressione lambda può essere utilizzata come espressione di funzione in un'applicazione come

[source,javascript]
----
((x, y, z) => x + y + quadrato(z))(1, 2, 3);
----

//or, more generally, in any context where we would normally use a function name.footnote:[It would be clearer and less intimidating to people learning JavaScript if a term more obvious than lambda expression, such as _function definition_ were used. But the convention is very firmly entrenched, not just for Lisp and Scheme but also for JavaScript, Java and other languages, no doubt partly due to the influence of the Scheme editions of this book. The notation is adopted from the latexmath:[$\lambda$] calculus, a mathematical formalism introduced by the mathematical logician Alonzo Church (1941). Church developed the latexmath:[$\lambda$] calculus to provide a rigorous foundation for studying the notions of function and function application. The latexmath:[$\lambda$] calculus has become a basic tool for mathematical investigations of the semantics of programming languages.] Note that `=>` has lower precedence than function application and thus the parentheses around the lambda expression are necessary here.
o, più in generale, in qualsiasi contesto in cui normalmente useremmo un nome di funzione.footnote:[Sarebbe più chiaro e meno intimidatorio per le persone che apprendono JavaScript se fosse usato un termine più ovvio dell'espressione lambda, come __definizione di funzione__. Ma la convenzione è molto ben radicata, non solo per Lisp e Scheme ma anche per JavaScript, Java e altri linguaggi, senza dubbio in parte a causa dell'influenza delle edizioni Scheme di questo libro. La notazione è adottata dal latexmath:[\lambda]-calcolo, un formalismo matematico introdotto dal logico matematico Alonzo Church (1941). Church ha sviluppato il latexmath:[\lambda]-calcolo per fornire una base rigorosa per lo studio delle nozioni di funzione e applicazione della funzione. Il latexmath:[\lambda]-calcolo è diventato uno strumento di base per le indagini matematiche sulla semantica dei linguaggi di programmazione.] Notare che "=>" ha una precedenza inferiore rispetto all'applicazione della funzione e quindi le parentesi attorno all'espressione lambda in questo esempio sono necessarie.

[[using-const-to-create-local-names]]
===== Uso di `const` per creare nomi locali

//Another use of lambda expressions is in creating local names. We often need local names in our functions other than those that have been bound as parameters. For example, suppose we wish to compute the function latexmath:[f(x,y)=x(1+xy)^2 +y(1-y)+(1+xy)(1-y]]
Un altro utilizzo delle espressioni lambda è nella creazione di nomi locali. Spesso abbiamo bisogno di nomi locali nelle nostre funzioni diversi da quelli che sono stati associati come parametri. Ad esempio, supponiamo di voler calcolare la funzione latexmath:[f(x,y)=x(1+xy)^2 +y(1-y)+(1+xy)(1-y]]

//which we could also express as
che potremmo anche esprimere come

[stem]
++++
\begin{aligned}
      a &=& 1+xy\\
      b &=& 1-y\\
      f(x,y) &=& xa^2 +yb +ab
\end{aligned}
++++

//In writing a function to compute latexmath:[$f$], we would like to include as local names not only latexmath:[$x$] and latexmath:[$y$] but also the names of intermediate quantities like latexmath:[$a$] and latexmath:[$b$]. One way to accomplish this is to use an auxiliary function to bind the local names:
Nello scrivere una funzione per calcolare latexmath:[f], vorremmo includere come nomi locali non solo latexmath:[x] e latexmath:[y] ma anche i nomi di quantità intermedie come latexmath:[a] e latexmath:[b]. Un modo per ottenere ciò è utilizzare una funzione ausiliaria per associare i nomi locali:

[source,javascript]
----
function f(x, y) {
    function f_ausiliaria(a, b) {
        return x * quadrato(a) + 
               y * b + 
               a * b;
    }
    return f_ausiliaria(1 + x * y,
                    1 - y);
}
----

//Of course, we could use a lambda expression to specify an anonymous function for binding our local names. The body of `f` then becomes a single call to that function:
Potremmo usare un'espressione lambda per specificare una funzione anonima per associare i nostri nomi locali. Il corpo di `f` diventa quindi una singola chiamata a quella funzione:

[source,javascript]
----
function f(x,y) {
    return ( (a, b) => x * quadrato(a) + 
                      y * b + 
                      a * b
           )(1 + x * y, 1 - y);
}
----

//A more convenient way to declare local names is by using constant declarations within the body of the function. Using `const`, the function `f` can be written as
Un modo più conveniente per dichiarare i nomi locali consiste nell'usare dichiarazioni di costanti all'interno del corpo della funzione. Usando "const", la funzione "f" può essere scritta come

[source,javascript]
----
function f(x, y) {
    const a = 1 + x * y;
    const b = 1 - y;
    return x * quadrato(a) + 
           y * b + 
           a * b;
}
----

//Names that are declared with `const` inside of a block have the body of the immediately surrounding block as their scope.[multiblock footnote omitted] Section [sec:internal-definitions] shows that declarations of local names can often be seen as syntactic sugar for applications of lambda expressions that have the declared names as parameters.
I nomi dichiarati con `const` all'interno di un blocco hanno come visibilità il corpo del blocco immediatamente circostante.
// La sezione TODO sec:internal-definition mostra che le dichiarazioni di nomi locali possono spesso essere viste come zucchero sintattico per applicazioni di espressioni lambda che hanno i nomi dichiarati come parametri.

[[conditional-statements]]
===== Istruzioni condizionali

//We have seen that it is often useful to declare names that are local to function declarations. When functions become big, we should keep the scope of the names as narrow as possible. Consider for example `expmod` in exercise [ex:louis-fast-prime].
Abbiamo visto che spesso è utile dichiarare nomi locali alle dichiarazioni di funzione. Quando le funzioni diventano grandi, dovremmo mantenere la visibilità dei nomi la più ristretta possibile. Considera ad esempio "potenza_modulo" in <<ex:louis-fast-prime>>.

[source,javascript]
----
function potenza_modulo(base, esponente, m) {
    return esponente === 0
           ? 1
           : pari(esponente)
             ? potenza_modulo(base, esponente / 2, m) 
               * potenza_modulo(base, esponente / 2, m)
               % m
             : base
               * potenza_modulo(base, esponente - 1, m) 
               % m;
}
----

//This function is unnecessarily inefficient, because it contains two identical calls:
Questa funzione è inutilmente inefficiente, perché contiene due chiamate identiche:

[source,javascript]
----
potenza_modulo(base, esponente / 2, m)
----

//While this can be easily fixed in this example using the `square` function, this is not so easy in general. Without using `square`, we would be tempted to introduce a local name for the expression as follows:
Anche se questo può essere facilmente risolto in questo esempio usando la funzione `quadrato`, non è così facile in generale. Senza usare "quadrato", saremmo tentati di introdurre un nome locale per l'espressione come segue:

[source,javascript]
----
function potenza_modulo(base, esponente, m) {
    const da_quadrare = potenza_modulo(base, esponente / 2, m);
    return esponente === 0
           ? 1
           : pari(esponente)
             ? da_quadrare
               * da_quadrare
               % m
             : base
               * potenza_modulo(base, esponente - 1, m) 
               % m;
}
----

//This would make the function not just inefficient, but actually non-terminating! The problem is that the constant declaration appears outside the conditional expression, which means that it is executed even when the base case `exp === 0` is met. To avoid this situation, we shall provide for _conditional statements_, and allow `return` statements to appear in several branches of the statement. Using a conditional statement, the function `expmod` can be written as follows:
Ciò renderebbe la funzione non solo inefficiente, ma addirittura non terminante! Il problema è che la dichiarazione della costante appare al di fuori dell'espressione condizionale, il che significa che viene eseguita anche quando viene soddisfatto il caso base `esponente === 0`. Per evitare questa situazione, il linguaggio fornisce le __istruzione condizionali__ e permette che le istruzioni `return` appaiano in rami diversi dell'istruzione condizionale. Utilizzando un'istruzione condizionale, la funzione `potenza_modulo` può essere scritta come segue:

[source,javascript]
----
function potenza_modulo(base, esponente, m) {
    if (esponente === 0) {
        return 1;
    } else {
        if (pari(esponente)) {
            const da_quadrare = potenza_modulo(base, esponente / 2, m);    
            return da_quadrare * da_quadrare % m;
        } else {
            return base * potenza_modulo(base, esponente - 1, m) % m;
        }
    }       
}
----

//The general form of a conditional statement is
La forma generale di un'istruzione condizionale è

.Forma generale di un'istruzione condizionale
****
**if (**__predicato__**) {** __conseguente__ **} else {** __alternativa__ **}**
****

//and, like conditional expressions, their evaluation first evaluates the latexmath:[$\textit{predicate}$]. If it evaluates to true, the interpreter evaluates the latexmath:[$\textit{consequent}$] statements and if it evaluates to false, the interpreter evaluates the latexmath:[$\textit{alternative}$] statements. Note that any constant declarations occurring in either part are local to that part, because both are enclosed in curly braces and thus form their own block.
e, come le espressioni condizionali, la loro valutazione prima valuta il __predicato__. Se restituisce true, l'interprete valuta le istruzioni _conseguente_ e se restituisce false, l'interprete valuta le istruzioni __alternativa__. Si noti che tutte le dichiarazioni di costanti che appaiono in una delle parti sono locali rispetto a quella parte, perché entrambe sono racchiuse tra parentesi graffe e quindi formano il proprio blocco.

.Esercizio 1.34. Applicazione di una funzione a se stessa
====
//Suppose we declare
Supponiamo di dichiarare

[source,javascript]
----
function f(g) {
   return g(2);
}
----

//Then we have
Poi abbiamo

[source,javascript]
----
f(quadrato);
----

[source,javascript]
----
f(z => z * (z + 1));
----

//What happens if we (perversely) ask the interpreter to evaluate the application `f(f)`? Explain.
Cosa succede se chiediamo (perversamente) all'interprete di valutare l'applicazione `f (f)`? Spiegarlo.
====

////
[[solution]]
==== Solution

Let’s use the substitution model to illustrate what happens:

[source,javascript]
----
f(f)
f(2)
2(2)
----

The application `2(2)` leads to an error, since 2 is neither a primitive nor a compound function.
////

//